<template>
  <yk-space size="xl">
    <yk-image
      src="https://www.huohuo90.com:3005/logo/yike.png"
      width="320"
      height="200"
      fit="cover"
      title="Yike-Design"
      description="包容万物，从源头出发，一切从简。"
    ></yk-image>
    <yk-image
      src="https://www.huohuo90.com:3005/logo/yike1.png"
      width="320"
      height="200"
      fit="cover"
      footer-position="outer"
      title="Yike-Design"
      description="包容万物，从源头出发，一切从简。"
    ></yk-image>
  </yk-space>
</template>
