<template>
  <yk-space wrap>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
    <yk-button>按钮</yk-button>
  </yk-space>
</template>
