/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/Bar.vue')['default']
    Codes: typeof import('./src/components/Codes.vue')['default']
    Dark: typeof import('./src/components/develops/dark.vue')['default']
    Grasp: typeof import('./src/components/develops/grasp.vue')['default']
    Modal: typeof import('./src/components/units/modal.vue')['default']
    Principle: typeof import('./src/components/design/principle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snippet: typeof import('./src/components/Snippet.vue')['default']
    Theme: typeof import('./src/components/develops/theme.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    Yikedesign: typeof import('./src/components/design/yikedesign.vue')['default']
    Yikedev: typeof import('./src/components/develops/yikedev.vue')['default']
    YkAlert: typeof import('./../packages/yike-design-ui/src/index.ts')['YkAlert']
    YkAvatar: typeof import('./../packages/yike-design-ui/src/index.ts')['YkAvatar']
    YkAvatarGroup: typeof import('./../packages/yike-design-ui/src/index.ts')['YkAvatarGroup']
    YkBackTop: typeof import('./../packages/yike-design-ui/src/index.ts')['YkBackTop']
    YkButton: typeof import('./../packages/yike-design-ui/src/index.ts')['YkButton']
    YkContainer: typeof import('./../packages/yike-design-ui/src/index.ts')['YkContainer']
    YkIcon: typeof import('./../packages/yike-design-ui/src/index.ts')['YkIcon']
    YkParagraph: typeof import('./../packages/yike-design-ui/src/index.ts')['YkParagraph']
    YkSpace: typeof import('./../packages/yike-design-ui/src/index.ts')['YkSpace']
    YkText: typeof import('./../packages/yike-design-ui/src/index.ts')['YkText']
    YkTheme: typeof import('./../packages/yike-design-ui/src/index.ts')['YkTheme']
    YkTitle: typeof import('./../packages/yike-design-ui/src/index.ts')['YkTitle']
    YkTooltip: typeof import('./../packages/yike-design-ui/src/index.ts')['YkTooltip']
  }
}
